spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shisanshui
    username: shisanshui
    password: Password1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        globally_quoted_identifiers: true

  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      initialize-schema: always
      table-name: SPRING_SESSION

server:
  port: 12300