spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shisanshui
    username: shisanshui
    password: Password1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
